openapi: "3.0.0"
info:
  version: 1.0.0
  title: Swagger UI Backend API
  license:
    name: MIT
paths:
  /products:
    get:
      summary: List all products
      operationId: listProducts
      tags:
        - products
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Products"
        default:
          description: unxexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        price:
          type: number
    Products:
      type: array
      items:
        $ref: "#/components/schemas/Product"
    Error:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string