version: "3"
services:
  dbsrv:
    image: snoman1/dbimg:V1
    ports:
      - "3306:3306"
    volumes:
      - testdbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=admin
  apisrv:
    image: snoman1/backend-app:V1
    ports:
      - "8080:8080"
volumes:
  testdbdata: {}