version: "3"
services:
  dbSrv:
    image: dbimg
    ports:
      - "3306:3306"
    volumes:
      - testdbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=admin
  backend:
    image: back-app
    ports:
      - "8080:8080"
volumes:
  testdbdata: {}